name: Compile LaTeX
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile LaTeX
        uses: xu-cheng/latex-action@main
        with:
          root_document: thesis.tex
          latexmk_options: "-pdf -bibtex -interaction=nonstopmode"
